name = "karuzelahajsu"
compatibility_date = "2026-10-06"
main = "worker.js"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "liga_db"
database_id = "25af5b31-ca0f-4ba9-a159-bce41c9c9760"